<?php
/** @var ViewModelRegistry $viewModels */
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Perspective\ProductReservation\ViewModel\FormData;
use Hyva\Theme\ViewModel\CurrentProduct;

/** @var Template $block */
$formUrl = $block->getUrl('perspectivereservation/reservation/order');

/** @var FormData $viewModel */
$viewModel = $viewModels->require(FormData::class);
/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

$productId = $currentProduct->get()->getId();
$customerData = [
    'name' => $viewModel->getCustomerFirstName(),
    'email' => $viewModel->getCustomerEmail(),
    'phone' => $viewModel->getCustomerPhone(),
];
?>

<div x-data="reservationModal()" x-cloak x-init="init(<?= $productId ?>)">
    <!-- Modal button-->
    <button
        type="button"
        class="ml-4 btn btn-primary"
        @click="openModal()"
    >
        <?= __('Reserve for 24h') ?>
    </button>

    <!-- Modal -->
    <div x-show="modalIsOpen"
         x-transition.opacity.duration.200ms
         @keydown.escape.window="closeModal()"
         @click.self="closeModal()"
         class="fixed inset-0 z-30 flex w-full items-start justify-end bg-black/20 p-4 pb-8 backdrop-blur-md lg:p-8"
         role="dialog"
         aria-modal="true"
         aria-labelledby="reservationModalTitle"
    >
        <div x-show="modalIsOpen"
             x-transition:enter="transition ease-out duration-200 delay-100"
             x-transition:enter-start="opacity-0 scale-50"
             x-transition:enter-end="opacity-100 scale-100"
             class="flex max-w-lg flex-col gap-4 overflow-hidden rounded-radius border border-outline bg-surface text-on-surface"
        >
            <!-- Header -->
            <div class="flex items-center justify-between border-b p-4">
                <h3 id="reservationModalTitle" class="font-semibold"><?= __('Reservation') ?></h3>
                <button @click="closeModal()" aria-label="Close modal">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="1.4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                </button>
            </div>

            <!-- Body / Form -->
            <div class="px-4 py-6">
                <template x-if="message">
                    <span x-text="message" class="mb-4 flex items-center justify-center"
                          :style="messageType === 'success' ? 'color: #16a34a;' : 'color: #dc2626;'">
                    </span>
                </template>

                <form id="reservation-form" @submit.prevent="submitForm">
                    <label class="block mb-1"><?= __('First Name') ?> *</label>
                    <input type="text" name="name" x-model="formData.name"
                           class="input-text w-full mb-3 border rounded px-2 py-1" required>

                    <label class="block mb-1"><?= __('Email') ?> *</label>
                    <input type="email" name="email" x-model="formData.email"
                           class="input-text w-full mb-3 border rounded px-2 py-1" required>

                    <label class="block mb-1"><?= __('Phone Number') ?></label>
                    <input type="tel" name="phone" x-model="formData.phone" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                           placeholder="123-456-7890" class="input-text w-full mb-3 border rounded px-2 py-1">

                    <button type="submit" :disabled="isSubmitting" class="btn btn-primary">
                        <span x-text="isSubmitting ? '<?= __('Processing...') ?>' : '<?= __('Submit') ?>'"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function reservationModal() {
        return {
            modalIsOpen: false, // modal open flag
            message: '', // success/error msg in modal
            messageType: '', // msg type
            isSubmitting: false, // form submitting flag
            productId: null,
            formData: <?= json_encode($customerData) ?>, // auto-filled data for logged customers

            openModal() {
                this.modalIsOpen = true;
                this.message = '';
                this.messageType = '';
            },

            closeModal() {
                this.modalIsOpen = false;
                this.message = '';
                this.messageType = '';
                this.isSubmitting = false;
            },

            // init Hyva event for get current simple product id from configurable
            init(productId) {
                this.productId = productId;
                window.addEventListener('configurable-selection-changed', (event) => {
                    const eventData = event.detail;
                    if (eventData) {
                        // set current product id
                        this.productId = eventData.productIndex;
                    }
                })
            },

            submitForm() {
                this.isSubmitting = true;

                //form
                let form = document.getElementById('reservation-form');
                let formData = new FormData(form);
                formData.append('form_key', hyva.getFormKey());

                // get selected qty from page
                let qtyInput = document.querySelector('input[name="qty"]');
                // set product id and qty to request data
                formData.append('qty', qtyInput.value);
                formData.append('product_id', this.productId);

                // send request
                fetch('<?= $formUrl ?>', {
                    method: 'POST',
                    body: formData,
                    credentials: 'include'
                })
                    // get json response from controller
                    .then(r => r.json())
                    .then(res => {
                        console.log(res);
                        this.isSubmitting = false;
                        this.message = res.message;
                        if (res.success) {
                            this.messageType = 'success';
                            setTimeout(() => this.closeModal(), 3500); // auto close modal if success
                        } else {
                            this.messageType = 'error';
                        }
                    });
            }
        }
    }
</script>
