<?php
use Perspective\MultiTabProductWidget\Block\Product\Widget\MultiTabProductList;
/** @var MultiTabProductList $block */

$tabsCount = 3;
?>

<div class="product data items"
     data-mage-init='{"mage/tabs": {"openedState": "active", "active": 0, "disabled": [], "disabledState": "disabled"}}'>
    <span style="font-weight:bold; position: relative; left: 45%; top: 10px; font-size: 18px;">
        <?= $block->escapeHtml($block->getWidgetTitle()) ?>
    </span>

    <?php for ($i = 1; $i <= $tabsCount; $i++): ?>
        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#widget_tab_<?= $i ?>">
                <?= $block->escapeHtml($block->getTabTitle($i)) ?>
            </a>
        </div>
        <div id="widget_tab_<?= $i ?>" class="item content" data-role="content">
            <?= $block->getProductListHtml($i) ?>
        </div>
    <?php endfor; ?>

</div>
